version: '2.1'
services:
  worker:
    extends:
      file: docker-compose.base.yml
      service: base
    command: ./manage.py celery worker --loglevel=INFO --events --beat --autoreload --concurrency=4 -Q mdn_purgeable,mdn_search,mdn_emails,mdn_wiki,celery
    depends_on:
      - mysql
      - elasticsearch
      - redis
      - kumascript

  web:
    extends:
      file: docker-compose.base.yml
      service: webbase
    command: gunicorn -w 4 --bind 0.0.0.0:8000 --access-logfile=- --timeout=120 --worker-class=meinheld.gmeinheld.MeinheldWorker kuma.wsgi:application
    ports:
      - "8000:8000"
    depends_on:
      - memcached
      - mysql
      - elasticsearch
      - redis
      - kumascript

  # API is used by KumaScript for content and metadata
  api:
    extends:
      file: docker-compose.base.yml
      service: webbase
    command: gunicorn -w 4 --bind 0.0.0.0:8000 --access-logfile=- --timeout=120 --worker-class=meinheld.gmeinheld.MeinheldWorker kuma.wsgi:application
    depends_on:
      - mysql
      - elasticsearch
      - redis
    ports:
      - "8001:8000"

  memcached:
    image: memcached

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_USER=kuma
      - MYSQL_PASSWORD=kuma
      - MYSQL_DATABASE=developer_mozilla_org
      - MYSQL_ROOT_PASSWORD=kuma
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --innodb-flush-log-at-trx-commit=0
      - --innodb-log-file-size=132M
      - --max-allowed-packet=100M
    volumes:
      - mysqlvolume:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data

  redis:
    image: redis

  kumascript:
    image: quay.io/mozmar/kumascript
    command: node run.js
    depends_on:
      - api
      - memcached
    environment:
      - interactive_examples__base_url=${INTERACTIVE_EXAMPLES_BASE:-https://interactive-examples.mdn.mozilla.net}
      - log__console=true
      - log__file=
      - server__template_root_dir=macros
      - server__document_url_template=http://api:8000/en-US/docs/{path}?raw=1
      - server__memcache__server=memcached:11211
      - server__template_class=EJSTemplate
      - server__autorequire__mdn=MDN:Common
      - server__autorequire__Page=DekiScript:Page
      - server__autorequire__String=DekiScript:String
      - server__autorequire__Uri=DekiScript:Uri
      - server__autorequire__Web=DekiScript:Web
      - server__autorequire__Wiki=DekiScript:Wiki
    ports:
      - "9080:9080"
    volumes:
      - ./kumascript:/app
volumes:
    mysqlvolume:
    esdata:
      driver: local
