#!/bin/bash -vx

# https://stackoverflow.com/a/246128/10612
SCRIPT_FOLDER="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
if [[ "$SCRIPT_FOLDER" == "." ]]
then
    SCRIPT_FOLDER=$PWD
fi
DOCKER_FOLDER=$(dirname $SCRIPT_FOLDER)
BASE_FOLDER=$(dirname $(dirname $(dirname $DOCKER_FOLDER)))

# Override Docker Hub
DOCKERFILE_PATH=$DOCKER_FOLDER/Dockerfile

# Set in Docker Hub
DOCKER_REPO=${DOCKER_REPO:-index.docker.io/jwhitlock/kuma_base}
CACHE_TAG=${CACHE_TAG:-test}
IMAGE_NAME=${IMAGE_NAME:-$DOCKER_REPO:$CACHE_TAG}

cd $BASE_FOLDER
echo ${PWD}: docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
